### ISSUE TITLE
Don't open external links in a new tab

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/blog#18]
Apparently this [isn't cool](https://ux.stackexchange.com/questions/5397/whats-your-take-on-target-blank) anymore.

Instead I should just have an indicator that the page is external, and allow my users to make the call themselves. #UX bro.

**Comment by rasoolsomji** [comment]
I could go either way on this issue but if you are looking at how your external links work, you could do something cool like the person [here](https://nintil.com/prove-wrong-get-money) does.

Check out the link to Donald Knuth in that second paragraph.

See also [gwern](https://www.gwern.net/Hydrocephalus) for all kinds of fun sub/superscripts and link goodness

**Comment by briggySmalls** [comment]
I went with a boring little arrow. Could change this in the future. Couldn't be bothered to dither 😂
