### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by rasoolsomji** [briggySmalls/blog#19]
Support those of us still using this old protocol

**Comment by briggySmalls** [comment]
It is actually available, at https://sambriggs.dev/posts/index.xml

I should make a link I suppose, highlighting this.

**Comment by rasoolsomji** [comment]
Ah thanks. I did try to find a link, and tried a few common suffixes but no dice

26 Apr 2020 11:00:17 briggySmalls <notifications@github.com>:
